using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ES2FactionRandomizer.Definitions.Traits
{
    public enum FactionTraitType
    {
        // Base Game
        FactionTraitAceSenatorsTitle,
        FactionTraitAmateurExecutivesTitle,
        FactionTraitReducedTaxesTitle,
        FactionTraitApatheticColonistsTitle,
        FactionTraitBeamSpecializationTitle,
        FactionTraitBigBrothersTitle,
        FactionTraitBigFleets1Title,
        FactionTraitBigFleets2Title,
        FactionTraitBigSpenders1Title,
        FactionTraitBigSpenders2Title,
        FactionTraitBlackThumb1Title,
        FactionTraitBlackThumb2Title,
        FactionTraitBlockadeBreakersTitle,
        FactionTraitBrilliantStrategists1Title,
        FactionTraitBrilliantStrategists2Title,
        FactionTraitBuilders1Title,
        FactionTraitBuilders2Title,
        FactionTraitBuilders3Title,
        FactionTraitBurningColonizationTitle,
        FactionTraitBusinessmen1Title,
        FactionTraitBusinessmen2Title,
        FactionTraitBusinessmen3Title,
        FactionTraitCombatRookiesTitle,
        FactionTraitCombatSpecialistsTitle,
        FactionTraitConfidentTacticiansTitle,
        FactionTraitContentCitizens1Title,
        FactionTraitContentCitizens2Title,
        FactionTraitCowards1Title,
        FactionTraitCowards2Title,
        FactionTraitCrowdedPlanets1Title,
        FactionTraitCrowdedPlanets2Title,
        FactionTraitCulturalists1Title,
        FactionTraitCulturalists2Title,
        FactionTraitDeadlyWeapons1Title,
        FactionTraitDeadlyWeapons2Title,
        FactionTraitDiligentWorkersTitle,
        FactionTraitDisciplinedTitle,
        FactionTraitDoubtfulTacticiansTitle,
        FactionTraitDryFrozenColonizationTitle,
        FactionTraitEfficientExplorer1Title,
        FactionTraitEfficientExplorer2Title,
        FactionTraitEternalWarTitle,
        FactionTraitExpansionists1Title,
        FactionTraitExpansionists2Title,
        FactionTraitExtendedConsortiumTitle,
        FactionTraitFactionTraitSmoothTalkersTitle,
        FactionTraitUtopianInfrastructureTitle,
        FactionTraitFastTraveler1Title,
        FactionTraitFastTraveler2Title,
        FactionTraitFearlessWarriors1Title,
        FactionTraitFearlessWarriors2Title,
        FactionTraitFeebleWarriors1Title,
        FactionTraitFeebleWarriors2Title,
        FactionTraitFerventColonists1Title,
        FactionTraitFerventColonists2Title,
        FactionTraitFierceVigilantesTitle,
        FactionTraitFloodedTemperateColonizationTitle,
        FactionTraitFrailVigilantesTitle,
        FactionTraitFrozenColonizationTitle,
        FactionTraitGasColonizationTitle,
        FactionTraitGeneHunterTitle,
        FactionTraitGrowthPlan1Title,
        FactionTraitGrowthPlan2Title,
        FactionTraitGrowthPlan3Title,
        FactionTraitGuardiansTitle,
        FactionTraitHotWetColonizationTitle,
        FactionTraitHumaneWeaponsTitle,
        FactionTraitIneptTradersTitle,
        FactionTraitInimicalTitle,
        FactionTraitKineticSpecializationTitle,
        FactionTraitKingpinExecutivesTitle,
        FactionTraitLaserSpecializationTitle,
        FactionTraitLegendaryHeroes1Title,
        FactionTraitLegendaryHeroes2Title,
        FactionTraitLousySenatorsTitle,
        FactionTraitLuxuryConnoisseursTitle,
        FactionTraitLuxuryIgnoramusesTitle,
        FactionTraitMissileSpecializationTitle,
        FactionTraitMutualUnderstanding1Title,
        FactionTraitMutualUnderstanding2Title,
        FactionTraitNaive1Title,
        FactionTraitNaive2Title,
        FactionTraitOptimalDefense1Title,
        FactionTraitOptimalDefense2Title,
        FactionTraitOptimistic1Title,
        FactionTraitOptimistic2Title,
        FactionTraitPatriots1Title,
        FactionTraitPatriots2Title,
        FactionTraitPerfectGenes1Title,
        FactionTraitPerfectGenes2Title,
        FactionTraitPessimistic1Title,
        FactionTraitPessimistic2Title,
        FactionTraitPoorStrategists1Title,
        FactionTraitPoorStrategists2Title,
        FactionTraitPriceOfPerfection1Title,
        FactionTraitPriceOfPerfection2Title,
        FactionTraitProneToAgitationTitle,
        FactionTraitPushovers1Title,
        FactionTraitPushovers2Title,
        FactionTraitScanningTitle,
        FactionTraitScientists1Title,
        FactionTraitScientists2Title,
        FactionTraitScientists3Title,
        FactionTraitSkillfulTradersTitle,
        FactionTraitSlowTraveler1Title,
        FactionTraitSlowTraveler2Title,
        FactionTraitSocialChameleonsTitle,
        FactionTraitSpaceCadets1Title,
        FactionTraitSpaceCadets2Title,
        FactionTraitStartWithHyperiumTitle,
        FactionTraitStartWithNegativeAnomalyTitle,
        FactionTraitStartWithPositiveAnomalyTitle,
        FactionTraitStartWithTitaniumTitle,
        FactionTraitSubOptimalDefenseTitle,
        FactionTraitTemperateColonizationTitle,
        FactionTraitUniqueDictatorshipTitle,
        FactionTraitUnskilledBuilders1Title,
        FactionTraitUnskilledBuilders2Title,    
        FactionTraitSacredTraditionTitle,                                    // Hissho (DLC2)
        FactionTraitHisshosFestivalsTitle,
        FactionTraitMiningExpertsTitle,
        FactionTraitPirateHatersTitle,
        FactionTraitJuggernautSpecialistsTitle,
        FactionTraitStartWithJuggernautTitle,
        FactionTraitReducedManpowerFromFoodTitle,                            // Umbral Choir (DLC3)
        FactionTraitManpowerFromProcessingPowerTitle,
        FactionTraitBonusHackingRoutesTitle,
        FactionTraitBonusHackingSpeedTitle,
        FactionTraitNativelyInvisibleShipsTitle,
        FactionTraitProcessingPowerFromTraitorsTitle,
        FactionTraitTradePenaltyTitle,
        FactionTraitLuxuryCostModifierTitle,
        FactionTraitAntiExpansionistsTitle

        // Nakalim (DLC4)
        /*
        FactionTraitTechnologicalHeadStartTitle                ,
        FactionTraitScienceReductionTitle                      ,
        FactionTraitMinorBonusDamageOnAcademyTitle             ,
        FactionTraitMinorBonusContributionToAcademyTitle       ,
        FactionTraitMinorOracularsTitle
        */

    }

    public class FactionTrait : FactionSetting
    {
        public FactionTrait(FactionTraitType iType, int iScoreModifier) : base(iType.ToString(), iScoreModifier)
        {
            _type = iType;
        }
        FactionTraitType _type { get; set; }
    }
}
